// unit comands and responses

export const STATUS = {
	MM: {
		varName: 'media',
		varDesc: 'Media Selection',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			US: { desc: 'USB', sub: {} },
			S1: { desc: 'SD Card 1', sub: {} },
			S2: { desc: 'SD Card 2', sub: {} },
			NE: { desc: 'Network', sub: {} },
		},
	},
	CD: {
		varName: 'sdcard',
		varDesc: 'SD Card Status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			CI: { desc: 'Card In', sub: {} },
			NC: { desc: 'No Card', sub: {} },
			CE: { desc: 'Card error', sub: {} },
			UF: { desc: 'Unformatted', sub: {} },
			WP: { desc: 'Write Protect', sub: {} },
			DO: { desc: 'Door Open', sub: {} },
		},
	},
	ST: {
		varName: 'status',
		varDesc: 'Device Status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			RE: { desc: 'Recording', sub: {} },
			RP: { desc: 'Record Pause', sub: {} },
			RU: { desc: 'DIR Unlocked', sub: {} },
			PL: { desc: 'Playing', sub: {} },
			AB: { desc: 'A-B Repeat Playing', sub: {} },
			PP: { desc: 'Paused', sub: {} },
			PR: { desc: 'A-B Repeat Paused', sub: {} },
			RW: { desc: 'rewinding', sub: {} },
			FF: { desc: 'Fast Forwarding', sub: {} },
			ST: { desc: 'Stopped', sub: {} },
			CU: { desc: 'Cued', sub: {} },
			CE: { desc: 'Cued', sub: {} },
			AC: { desc: 'Auto-cued', sub: {} },
			SH: { desc: 'Timer standby', sub: {} },
			LD: { desc: 'Loading', sub: {} },
			BY: { desc: 'Busy', sub: {} },
			FL: { desc: 'File List Opening', sub: {} },
			ED: { desc: 'Main Menu opening', sub: {} },
			ER: { desc: 'Operation error', sub: {} },
		},
	},
	// no response from device on query
	// ER: {
	// 	varName: 'last_err',
	// 	varDesc: 'Last error code',
	// 	isRequest: false,
	// 	subLen: 0,
	// 	opt: {},
	// },
	Tr: {
		varName: 'track_cur',
		varDesc: 'Current Track #',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	Sf: {
		varName: 'folder_cur',
		varDesc: 'Current Folder #',
		isRequest: false,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	SF: {
		varName: 'folder_name',
		varDesc: 'Current Folder Name',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	Tt: {
		varName: 'track_tot',
		varDesc: 'Total Tracks',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	Tf: {
		varName: 'folder_tot',
		varDesc: 'Total Folders',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	PW: {
		varName: 'power',
		varDesc: 'Power status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
			'02': { desc: 'Standby', sub: {} },
		},
	},
	Ia: {
		varName: 'login_req',
		varDesc: 'Login required',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			'00': { desc: 'Yes', sub: {} },
			'01': { desc: 'No', sub: {} },
		},
	},
	LI: {
		varName: 'login_ok',
		varDesc: 'Login Password Status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			OK: { desc: 'Login OK', sub: {} },
			NG: { desc: 'Login failed', sub: {} },
		},
	},
	PO: {
		varName: 'power_on',
		varDesc: 'Power On Mode',
		subLen: 0,
		isRequest: true,
		hasLR: false,
		opt: {
			RM: { desc: 'Resume playback', sub: {} },
			PF: { desc: 'Play first track', sub: {} },
			ST: { desc: 'Stopped', sub: {} },
			RE: { desc: 'Record', sub: {} },
		},
	},
	FE: {
		varName: 'media_free',
		varDesc: 'Free space on Media',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			S1: { desc: 'SD1', sub: {} },
			S2: { desc: 'SD2', sub: {} },
			US: { desc: 'USB', sub: {} },
		},
	},
	//	SF:
	SP: {
		varName: 'search_spd',
		varDesc: 'Search Speed',
		isRequest: true,
		subLen: 1,
		hasLR: false,
		opt: {
			F: { desc: 'FF', sub: {} },
			R: { desc: 'RW', sub: {} },
		},
	},
	IN: {
		varName: 'rec_input',
		varDesc: 'Recording Input',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			UB: { desc: 'Unbalanced (RCA)', sub: {} },
			BA: { desc: 'Balanced (XLR)', sub: {} },
			DI: { desc: 'Digital (RCA)', sub: {} },
			DB: { desc: 'Digital (AES))', sub: {} },
		},
	},
	OR: {
		varName: 'rec_otr',
		varDesc: 'One Touch Record',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	PR: {
		varName: 'rec_pre',
		varDesc: 'Pre-record time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	Rf: {
		varName: 'rec_folder',
		varDesc: 'Recording Folder',
		subLen: 1,
		isRequest: true,
		hasLR: false,
		opt: {
			C: { desc: 'Current Folder', sub: {} },
			F: { desc: 'Folder', sub: {} },
		},
	},
	RT: {
		varName: 'rec_remain',
		varName: 'Remaining Record Time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	RV: {
		varName: 'rec_volume',
		varDesc: 'Record Volume (LLRR)',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	VI: {
		varName: 'rec_vol_type',
		varDesc: 'Record Volume Type',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			FX: { desc: 'Fixed at 0dB', sub: {} },
			VA: { desc: 'Variable', sub: {} },
		},
	},
	Rm: {
		varName: 'rec_mon',
		varDesc: 'Record Monitor',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	AT: {
		varName: 'rec_split',
		varDesc: 'Split record at Time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	Rl: {
		varName: 'knob',
		varDesc: 'Level Knob Mode',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			MA: { desc: 'Volume (push Pan)', sub: {} },
			LR: { desc: 'Pan, (push Vol)', sub: {} },
		},
	},
	RL: {
		varName: 'alc',
		varDesc: 'ALC Control',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			MA: { desc: 'Off', sub: {} },
			SE: { desc: 'Left/Right Separate', sub: {} },
			MI: { desc: 'Left/Right Mixed', sub: {} },
		},
	},
	dR: {
		varName: 'rec_dual',
		varDesc: 'Dual Media Recording',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			OF: { desc: 'Off', sub: {} },
			S1: { desc: 'SD1', sub: {} },
			S2: { desc: 'SD2', sub: {} },
			US: { desc: 'USB', sub: {} },
		},
	},
	rR: {
		varName: 'rec_relay',
		varDesc: 'Relay Media Recording',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			OF: { desc: 'Off', sub: {} },
			S1: { desc: 'SD1', sub: {} },
			S2: { desc: 'SD2', sub: {} },
			US: { desc: 'USB', sub: {} },
		},
	},
	AR: {
		varName: 'archive',
		varDesc: 'Archive Mode',
		isRequest: 0,
		subLen: 0,
		hasLR: false,
		opt: {
			'01': { desc: 'Off', sub: {} },
			AT: { desc: 'Archive at end of record', sub: {} },
			SC: { desc: 'Archive at scheduled time', sub: {} },
		},
	},
	CA: {
		varName: 'rec_auto',
		varDesc: 'Auto Delete after archiving',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	AD: {
		varName: 'rec_space',
		varDesc: 'Delete for space',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			OF: { desc: 'Off', sub: {} },
			'01': { desc: 'Less than 1 hour', sub: {} },
			'03': { desc: 'Less than 3 hours', sub: {} },
			'06': { desc: 'Less than 6 hours', sub: {} },
			12: { desc: 'Less than 12 hours', sub: {} },
			24: { desc: 'Less than 24 hours', sub: {} },
		},
	},
	CH: {
		varName: 'rec_channel',
		varDesc: 'Record Which Channel',
		isRequest: true,
		sublen: 0,
		hasLR: false,
		opt: {
			ST: { desc: 'Stereo', sub: {} },
			ML: { desc: 'Mono Left', sub: {} },
			MR: { desc: 'Mono Right', sub: {} },
		},
	},
	AF: {
		varName: 'rec_fmt',
		varDesc: 'Recording format',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			PM: {
				desc: 'PCM',
				sub: {
					24: '24 bit',
					32: '32 bit',
				},
			},
			M3: {
				desc: 'MP3',
				sub: {
					'064': '64K bps',
					128: '128K bps',
					192: '192K bps',
					256: '256K bps',
					320: '320K bps',
				},
			},
		},
	},
	FS: {
		varName: 'rec_rate',
		varDesc: 'Recording sample rate',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			44: { desc: '44 kHz', sub: {} },
			48: { desc: '48 kHz', sub: {} },
			96: { desc: '96 kHz', sub: {} },
			EX: { desc: 'External', sub: {} },
		},
	},
	Ff: {
		varName: 'fn_format',
		varDesc: 'File Name Format',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			MDU: { desc: 'Machine + Date + User', sub: {} },
			MUD: { desc: 'Machine + User + Date', sub: {} },
			DMU: { desc: 'Date + Machine + User', sub: {} },
			DUM: { desc: 'Date + User + Machine', sub: {} },
			UMD: { desc: 'User + Machine + Date', sub: {} },
			UDM: { desc: 'User + Date + Machine', sub: {} },
		},
	},
	UA: {
		varName: 'ua_data',
		varDesc: 'User Area Data',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	US: {
		varName: 'ua_inc',
		varDesc: 'Include User Area in File Name',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	MN: {
		varName: 'dev_name',
		varDesc: 'Device (Machine) Name',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	ti: {
		varName: 'title',
		varDesc: 'Track Title',
		isRequest: false,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	at: {
		varName: 'artist',
		varDesc: 'Artist',
		isRequest: false,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	al: {
		varName: 'album',
		varDesc: 'Album Title',
		isRequest: false,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	af: {
		varName: 'track_fmt',
		varDesc: 'Track format',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			PM: {
				desc: 'PCM',
				sub: {
					24: '24 bit',
					32: '32 bit',
				},
			},
			M3: {
				desc: 'MP3',
				sub: {
					'064': '64K bps',
					128: '128K bps',
					192: '192K bps',
					256: '256K bps',
					320: '320K bps',
				},
			},
		},
	},
	tl: {
		varName: 'track_len',
		varDesc: 'Track Length (MMMSSFF)',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	ET: {
		varName: 'track_et',
		varDesc: 'Track Elapsed (HHHMMSS)',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	RM: {
		varName: 'track_rt',
		varDesc: 'Track Remaining (HHHMMSS)',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	FR: {
		varName: 'file_sort',
		varDesc: 'File List Sort',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			AL: { desc: 'Alpha', sub: {} },
			DA: { desc: 'Date', sub: {} },
		},
	},
	UL: {
		varName: 'list_updated',
		varDesc: 'File list update status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'Unchanged', sub: {} },
			'01': { desc: 'Updated', sub: {} },
		},
	},
	pR: {
		varName: 'pb_range',
		varDesc: 'Playback Range',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			AL: { desc: 'Current media', sub: {} },
			FD: { desc: 'Current Folder', sub: {} },
		},
	},
	PM: {
		varName: 'pb_mode',
		varDesc: 'Playback Mode',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			SP: { desc: 'Single Play', sub: {} },
			CN: { desc: 'Play Tracklist', sub: {} },
		},
	},
	RN: {
		varName: 'pb_random',
		varDesc: 'Playback Random',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'01': { desc: 'On', sub: {} },
			'00': { desc: 'Off', sub: {} },
		},
	},
	RE: {
		varName: 'pb_repeat',
		varDesc: 'Playback Random',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	PG: {
		varName: 'pl_status',
		varDesc: 'Program List Status',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'No List', sub: {} },
			'01': { desc: 'Loaded', sub: {} },
		},
	},
	tP: {
		varName: 'pl_count',
		varDesc: 'Program List Count',
		isRequest: false,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	pl: {
		varName: 'pl_name_00',
		varDesc: 'Program List Name',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {},
	},
	FM: {
		varName: 'finish',
		varDesc: 'Stop finish mode',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			ST: { desc: 'Stop playback', sub: {} },
			NT: { desc: 'Cue next track', sub: {} },
			RC: { desc: 'Recue to start', sub: {} },
		},
	},
	AC: {
		varName: 'autocue',
		varDesc: 'Skip quiet start of track',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'Off', sub: {} },
			36: { desc: 'Below 36dB', sub: {} },
			42: { desc: 'Below 42dB', sub: {} },
			48: { desc: 'Below 48dB', sub: {} },
		},
	},
	Sp: {
		varName: 'pass_thru',
		varDesc: 'Record input pass-through',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	Sh: {
		varName: 'rec_schedule_00',
		varDesc: 'Record schedule 00',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			DW: { desc: 'Day of Week', sub: {} },
			DT: { desc: 'Date and Time', sub: {} },
		},
	},
	TP: {
		varName: 'pb_schedule_00',
		varDesc: 'Playback schedule 00',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			DW: { desc: 'Day of Week', sub: {} },
			DT: { desc: 'Date and Time', sub: {} },
		},
	},
	as: {
		varName: 'ar_sched',
		varDesc: 'Archive schedule',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			DW: { desc: 'Day of Week', sub: {} },
			DT: { desc: 'Date and Time', sub: {} },
		},
	},
	Ct: {
		varName: 'cur_sch',
		varDesc: 'Current Timer Schedule',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			RE: { desc: 'Record', sub: {} },
			PL: { desc: 'Playback', sub: {} },
		},
	},
	Rt: {
		varName: 'res_sch',
		varDesc: 'Reserved Timer',
		isRequest: false,
		subLen: 2,
		hasLR: false,
		opt: {
			RE: { desc: 'Record', sub: {} },
			PL: { desc: 'Playback', sub: {} },
		},
	},
	tp: {
		varName: 'sch_priority',
		varDesc: 'Schedule (timer) Priority',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'Start if not recording', sub: {} },
			'01': { desc: 'Start if Stop/Pause/Standby', sub: {} },
		},
	},
	PT: {
		varName: 'pitch_speed',
		varDesc: 'Pitch/Speed Setting',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			ON: { desc: 'On', sub: {} },
			OF: { desc: 'Off', sub: {} },
		},
	},
	KY: {
		varName: 'speed_only',
		varDesc: 'Pitch and Speed Setting',
		isRequest: true,
		subLen: 2,
		hasLR: false,
		opt: {
			'00': { desc: 'Speed Only', sub: {} },
			'01': { desc: 'Pitch and Speed', sub: {} },
		},
	},
	Tm: {
		varName: 'mark_total',
		varDesc: 'Total Marks on Track',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	AM: {
		varName: 'mark_auto',
		varDesc: 'Auto Marking',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	SS: {
		varName: 'skip_silent',
		varDesc: 'Skip Silent Parts during Playback',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	SB: {
		varName: 'skip_back',
		varDesc: 'Skip Back Time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	FI: {
		varName: 'fade_in',
		varDesc: 'Fade In Time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	FO: {
		varName: 'fade_out',
		varDesc: 'Fade Out Time',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	sD: {
		varName: 'pb_delay',
		varDesc: 'Playback Delay',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	ED: {
		varName: 'end_msg',
		varDesc: 'Time to Display Track End Message',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {},
	},
	ch: {
		varName: 'track_ch',
		varDesc: 'Track Channel type',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			ST: { desc: 'Stereo', sub: {} },
			MO: { desc: 'Mono', sub: {} },
		},
	},
	sM: {
		varName: 'search_mode',
		varDesc: 'Play audio while searching',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			NO: { desc: 'Play', sub: {} },
			SL: { desc: 'Silent', sub: {} },
		},
	},
	MO: {
		varName: 'pb_mono',
		varDesc: 'Playback Mono Mode',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			ST: { desc: 'Stereo', sub: {} },
			MO: { desc: 'Mono', sub: {} },
		},
	},
	dF: {
		varName: 'audio_rate',
		varDesc: 'Digital Audio Sample Rate',
		isRequest: true,
		subLen: 0,
		hasLR: false,
		opt: {
			AT: { desc: 'Auto', sub: {} },
			44: { desc: '44.1 kHz', sub: {} },
			48: { desc: '48 kHz', sub: {} },
			EX: { desc: 'External', sub: {} },
		},
	},
	It: {
		varName: 'input',
		varDesc: 'Input Adjust',
		isRequest: true,
		subLen: 0,
		hasLR: true,
		opt: {},
	},
	Ot: {
		varName: 'output',
		varDesc: 'Output Adjust',
		isRequest: true,
		subLen: 0,
		hasLR: true,
		opt: {},
	},
	LM: {
		varName: 'xlr_lvl',
		varDesc: 'Input Level',
		isRequest: true,
		subLen: 0,
		hasLR: true,
		opt: {
			LN: { desc: 'Line', sub: {} },
			MC: { desc: 'Mic', sub: {} },
		},
	},
	Ph: {
		varName: 'xlr_pp',
		varDesc: 'XLR Phantom Power',
		isRequest: true,
		subLen: 0,
		hasLR: true,
		opt: {
			'00': { desc: 'On', sub: {} },
			'01': { desc: 'Off', sub: {} },
		},
	},
	Ms: {
		varName: 'xlr_mic',
		varDesc: 'XLR Mic Sensitivity',
		isRequest: true,
		subLen: 0,
		hasLR: true,
		opt: {},
	},
}
